apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://192.168.122.1:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://192.168.122.1:3100
