server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.122.1:3100/loki/api/v1/push
    backoff_config:
    minbackoff: 1s
    maxbackoff: 10s
    maxretries: 5

scrape_configs:
  - job_name: varlogs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/dpkg.log
